name: Code Quality (Lint & Format)

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  quality-check:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Acá podés agregar pasos para copiar los archivos a la carpeta local que quieras
      - name: Copiar archivos a mi carpeta de desarrollo
        shell: cmd
        run: |
          xcopy . "C:\Users\Marcio\Downloads\Curso 17hs\publicar" /E /I /Y  # (En Windows)
          # o 'cp -r . /var/www/miapp' si estás en una Raspberry o Linux

      # 2. Configura el entorno de Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Podés cambiarlo por la versión de Node que uses
          cache: 'npm'

      # 3. Instala las dependencias del proyecto de forma limpia
      # Usamos --legacy-peer-deps por el conflicto de versiones que tuvimos antes
      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      # 4. Corre el chequeo de formateo de Prettier
      # El flag --check hace que falle si encuentra archivos mal formateados sin editarlos
      - name: Run Prettier check
        run: npx prettier --check .

      # 5. Corre el validador de ESLint
      - name: Run ESLint
        run: npx eslint .
